name: digital_profile
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.67.0
  equatable: ^2.0.5
  bloc: ^8.1.4
  http:
  flutter_localization: ^0.2.0
  cupertino_icons: ^1.0.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dio: ^5.4.3+1
  flutter_bloc: ^8.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  injectable_generator: ^1.5.5
  mocktail: ^0.3.0
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1

flutter:
  assets:
    - assets/familyData.json
    - assets/population_count.json


  uses-material-design: true