name: digital_profile
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+11

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.67.0
  equatable: ^2.0.5
  bloc: ^8.1.4
  http:
  flutter_localization: ^0.2.0
  cupertino_icons: ^1.0.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dio: ^5.4.3+1
  flutter_bloc: ^8.1.5
  flutter_table: ^1.1.0
  shared_preferences: ^2.2.3
  logger: any
  get_it: ^7.7.0
  url_launcher: ^6.3.0
  flutter_map: ^7.0.1
  latlong2: ^0.9.1
  drift: ^2.18.0
  path: ^1.9.0
  connectivity_plus: ^2.0.2
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  flutter_native_splash: ^2.4.1

flutter_native_splash:
  color: "#051f1f"
  android: true
  ios: true
  image : assets/images/splash_scrren_icon1.png
  android_12 :
    color: "#051f1f"
    image : assets/images/splash_scrren_icon1.png
    android_gravity: center
    ios_content_mode: center
    fullscreen : true

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  injectable_generator: ^1.5.5
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  drift_dev: ^2.18.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: lib/app_localization/arb
  output_dir: lib/app_localization/generated

